FROM postgres:alpine3.18
COPY ${PWD}/postgres-bootstrap.sql /docker-entrypoint-initdb.d/
COPY ${PWD}/postgresql.conf /usr/local/share/postgresql/postgresql.conf
COPY ${PWD}/postgresql.conf /usr/local/share/postgresql/pg_hba.conf